export const opciones = {
    fortamun: [
      { value: "seguridad_publica", label: "Seguridad Publica" },
      { value: "otros", label: "Otros" },
    ],
    faismun11: [ 
      { value: "zona_atencion_prioritaria", label: "Zona de atencion prioritaria" },
      { value: "incidencia_directa", label: "Incidencia Directa" },
      { value: "indirectos", label: "Indirectos" },
      { value: "prodim", label: "PRODIM" },
      { value: "incidencia_complementaria", label: "Incidencia Complementaria" },
    ],
    faismun10: [
        { value: "zona_atencion_prioritaria", label: "Zona de atencion prioritaria" },
        { value: "incidencia_directa", label: "Incidencia Directa" },
        { value: "indirectos", label: "Indirectos" },
        { value: "incidencia_complementaria", label: "Incidencia Complementaria" },
      ],
      faismun01: [
        { value: "zona_atencion_prioritaria", label: "Zona de atencion prioritaria" },
        { value: "incidencia_directa", label: "Incidencia Directa" },
        { value: "prodim", label: "PRODIM" },
        { value: "incidencia_complementaria", label: "Incidencia Complementaria" },
      ],
      faismun00: [
        { value: "zona_atencion_prioritaria", label: "Zona de atencion prioritaria" },
        { value: "incidencia_directa", label: "Incidencia Directa" },
        { value: "incidencia_complementaria", label: "Incidencia Complementaria" },
      ],
    default: [
      { value: "default1", label: "Opción por Defecto 1" },
      { value: "default2", label: "Opción por Defecto 2" },
    ],
  };


  export const opcionesPrograma = {
    fortamun: [
      { value: "CO-SEGURIDAD PUBLICA", label: "C0-SEGURIDAD PUBLICA" },
      { value: "F1-FORTALECIMIENTO INSTITUCIONAL MUNICIPAL", label: "F1-FORTALECIMIENTO INSTITUCIONAL MUNICIPAL" },
      { value: "SC-AGUA POTABLE", label: "SC-AGUA POTABLE" },
      { value: "SD-ALCANTARILLADO", label: "SD-ALCANTARILLADO" },
      { value: "SE-URBANIZACION", label: "SE-URBANIZACION" },
      { value: "SE-URBANIZACION", label: "SE-URBANIZACION" },
      { value: "SF-PAVIMENTACION EN COLONIAS POPULARES", label: "SF-PAVIMENTACION EN COLONIAS POPULARES" },
      { value: "SG-ELECTRIFICACION", label: "SG-ELECTRIFICACION" },
      { value: "SH-VIVIENDA DIGNA", label: "SH-VIVIENDA DIGNA" },
      { value: "SI-VIALIDADES URBANAS", label: "SI-VIALIDADES URBANAS" },
      { value: "SJ-INFRAESTRUCTURA EDUCATIVA", label: "SJ-INFRAESTRUCTURA EDUCATIVA" },
      { value: "SL-INFRAESTRUCTURA DEPORTIVA", label: "SL-INFRAESTRUCTURA DEPORTIVA" },
      { value: "SO-CENTROS DE SALUD", label: "SO-CENTROS DE SALUD" },
      { value: "SP-UNIDADES MEDICAS RURALES", label: "SP-UNIDADES MEDICAS RURALES" },
      { value: "SS-ASISTENCIA SOCIAL Y SERVICIOS COMUNITARIOS", label: "SS-ASISTENCIA SOCIAL Y SERVICIOS COMUNITARIOS" },
      { value: "S5-PROTECCION Y PRESERVACION ECOLOGIGA", label: "S5-PROTECCION Y PRESERVACION ECOLOGIGA" },
      { value: "TB-MUJERES", label: "TB-MUJERES" },
      { value: "TE-APOYO A LA PRODUCCION PRIMARIA", label: "TE-APOYO A LA PRODUCCION PRIMARIA"},
      { value: "TF-FOMENTO A LA PRODUCCION Y PRODUCTIVIDAD", label: "TF-FOMENTO A LA PRODUCCION Y PRODUCTIVIDAD"},
      { value: "TG-DESARROLLO DE AREAS DE RIESGO (PEQUEÑA IRRIGACION)", label: "TG-DESARROLLO DE AREAS DE RIESGO (PEQUEÑA IRRIGACION)"},
      { value: "TH-DESARROLLO DE AREAS DE TEMPORAL", label: "TH-DESARROLLO DE AREAS DE TEMPORAL"},
      { value: "TI-PROTECCION DE AREAS Y CAUCES FEDERALES", label: "TI-PROTECCION DE AREAS Y CAUCES FEDERALES"},
      { value: "UB-CAMINOS RURALES", label: "UB-CAMINOS RURALES"},
      { value: "UE-SITIOS HISTORICOS Y CULTURALES", label: "UE-SITIOS HISTORICOS Y CULTURALES"},
      { value: "UH-INFRAESTRUCTURA PENINTENCIARIA", label: "UH-INFRAESTRUCTURA PENINTENCIARIA"},
      { value: "U9-DEFINICION Y CONDUCCION DE LA PLANEACION DEL DESARROLLO REGIONAL", label: "U9-DEFINICION Y CONDUCCION DE LA PLANEACION DEL DESARROLLO REGIONAL"},
      { value: "3Z-REGULACION Y PRESERVACION ECOLOGICA", label: "3Z-REGULACION Y PRESERVACION ECOLOGICA"},
      { value: "5C-ESTABLECIMIENTOS TURISTICOS Y DE ESPARCIMIENTO", label: "5C-ESTABLECIMIENTOS TURISTICOS Y DE ESPARCIMIENTO"},
      { value: "5G-AMPLIACION Y MEJORAMIENTO DE LA PLANTA FISICA PARA LA INVESTIGACION CIENTIFICA Y TECNOLOGICA", label: "5G-AMPLIACION Y MEJORAMIENTO DE LA PLANTA FISICA PARA LA INVESTIGACION CIENTIFICA Y TECNOLOGICA"},
      { value: "5I-EDIFICIOS PARA SERVICIOS DE SALUD Y SEGURIDAD SOCIAL", label: "5I-EDIFICIOS PARA SERVICIOS DE SALUD Y SEGURIDAD SOCIAL"},
      { value: "5K-EDIFICIOS ADMINISTRATIVOS", label: "5K-EDIFICIOS ADMINISTRATIVOS"},
      { value: "5L-SUELO PARA DESARROLLO URBANO, VIVIENDA Y ECOLOGIA", label: "5L-SUELO PARA DESARROLLO URBANO, VIVIENDA Y ECOLOGIA"},
      { value: "6P-CANALIZACION DE RECURSOS FINANCIEROS", label: "6P-CANALIZACION DE RECURSOS FINANCIEROS"},
    ],
    faismun: [ 
      { value: "0101-SISTEMA DE AGUA POTABLE", label: "0101-SISTEMA DE AGUA POTABLE" },
      { value: "0102-POZO PROFUNDO DE AGUA POTABLE", label: "0102-POZO PROFUNDO DE AGUA POTABLE" },
      { value: "0103-DEPOSITO O TANQUE DE AGUA POTABLE", label: "0103-DEPOSITO O TANQUE DE AGUA POTABLE"},
      { value: "0104-NORIAS", label: "0104-NORIAS"},
      { value: "0105-1.5-BOMBAS Y EQUIPO", label: "0105-1.5-BOMBAS Y EQUIPO"},
      { value: "0136-PROYECTOS EJECUTIVO", label: "0136-PROYECTOS EJECUTIVO"},
      { value: "0140-OTROS(ESPECIFICAR)", label: "0140-OTROS(ESPECIFICAR)"},
      { value: "0308-RED DE DRENAJE PRUVIAL", label: "0308-RED DE DRENAJE PRUVIAL"},
      { value: "0309-RED DE DRENAJE SANITARIO", label: "0309-RED DE DRENAJE SANITARIO"},
      { value: "0310-LETRINAS", label: "0310-LETRINAS"},
      { value: "0336-PROYECTO EJECUTIVO", label: "0336-PROYECTO EJECUTIVO"},
      { value: "0340-OTROS(ESPECIFICAR)", label: "0340-OTROS(ESPECIFICAR)"},
      { value: "0411-CALLES Y CAMINOS", label: "0411-CALLES Y CAMINOS"},
      { value: "0412-PUENTES PEATONALES O VEHICULARES", label: "0412-PUENTES PEATONALES O VEHICULARES"},
      { value: "0413-PASOS PEATONALES Y/O VEHICULARES", label: "0413-PASOS PEATONALES Y/O VEHICULARES"},
      { value: "0414-RELLENO SANITARIO", label: "0414-RELLENO SANITARIO"},
      { value: "0415-TRATAMIENTO DE AGUAS RESIDUALES", label: "0415-TRATAMIENTO DE AGUAS RESIDUALES"},
      { value: "0436-PROYECTO EJECUTIVO", label: "0436-PROYECTO EJECUTIVO"},
      { value: "0440-OTROS(ESPECIFICAR)", label: "0440-OTROS(ESPECIFICAR)"},
      { value: "0519-RED DE ELECTRICIDAD",label: "0519-RED DE ELECTRICIDAD"},
      { value: "0520-ALUMBRADO PUBLICO",label: "0520-ALUMBRADO PUBLICO"},
      { value: "0540-OTROS(ESPECIFICAR)",label:"0540-OTROS(ESPECIFICAR)"},
      { value: "0621-CENTROS DE SALUD",label:"0621-CENTROS DE SALUD"},
      { value: "0622-DISPENSADOR MEDICO Y UNIDADES MEDICAS RURALES",label:"0622-DISPENSADOR MEDICO Y UNIDADES MEDICAS RURALES"},
      { value: "0623-LABORATORIOS DE ANALISIS CLINICOS",label:"0623-LABORATORIOS DE ANALISIS CLINICOS"},
      { value: "0636-PROYECTO EJECUTIVO",label:"0636-PROYECTO EJECUTIVO"},
      { value: "0640-OTROS(ESPECIFICAR)",label:"0640-OTROS(ESPECIFICAR)"},
      { value: "0724-AULAS",label:"0724-AULAS"},
      { value: "0725-SANITARIOS DENTRO DE ESCUELAS",label:"0725-SANITARIOS DENTRO DE ESCUELAS"},
      { value: "0726-BARDAS DE ESCUELA",label:"0726-BARDAS DE ESCUELA"},
      { value: "0727-ESCALERAS Y ANDADORES DENTRO DE ESCUELAS",label:"0727-ESCALERAS Y ANDADORES DENTRO DE ESCUELAS"},
      { value: "0736-PROYECTO EJECUTIVO",label:"0736-PROYECTO EJECUTIVO"},
      { value: "0740-OTROS(ESPECIFICAR)",label:"0740-OTROS(ESPECIFICAR)"},
      { value: "0829-PISO FIRME",label:"0829-PISO FIRME"},
      { value: "0830-VIVIENDA",label:"0830-VIVIENDA"},
      { value: "0931-CAMINOS RURALES",label:"0931-CAMINOS RURALES"},
      { value: "0936-PROYECTO EJECUTIVO",label:"0936-PROYECTO EJECUTIVO"},
      { value: "0940-OTROS(ESPECIFICAR)",label:"0940-OTROS(ESPECIFICAR)"},

    ],

    default: [
      { value: "default1", label: "Opción por Defecto 1" },
      { value: "default2", label: "Opción por Defecto 2" },
    ],
  };



  export const opcionesSubprograma = {

    "CO-SEGURIDAD PUBLICA": [
    { value: "01-ADMINISTRACION", label: "01-ADMINISTRACION" },
    { value: "02-SERVICIOS", label: "02-SERVICIOS" },
    { value: "03-ADQUISICIONES", label: "03-ADQUISICIONES" },
    ],

    "F1-FORTALECIMIENTO INSTITUCIONAL MUNICIPAL": [
    { value: "01-ADMINISTRACION", label: "01-ADMINISTRACION" },
    { value: "02-SERVICIOS", label: "02-SERVICIOS" },
    { value: "03-ADQUISICIONES", label: "03-ADQUISICIONES" },    
    ],

    "SC-AGUA POTABLE": [
    { value: "01-REHABILITACION", label: "01-REHABILITACION" }, 
    { value: "02-AMPLIACION", label: "02-AMPLIACION" }, 
    { value: "03-CONSTRUCCION", label: "03-CONSTRUCCION"},
    { value: "04-LINEAS DE CONDUCCION DE AGUA", label: "04-LINEAS DE CONDUCCION DE AGUA"},
    { value: "05-DOTACION DE AGUA", label: "05-DOTACION DE AGUA"},
    { value: "06-ESTUDIOS Y PROYECTOS", label: "06-ESTUDIOS Y PROYECTOS"},  
    ],

    "SD-ALCANTARILLADO": [
        { value: "01-REHABILITACION", label: "01-REHABILITACION" }, 
        { value: "02-AMPLIACION", label: "02-AMPLIACION" }, 
        { value: "03-CONSTRUCCION", label: "03-CONSTRUCCION"},
        { value: "04-ESTUDIOS Y PROYECTOS", label: "04-ESTUDIOS Y PROYECTOS"},  
    ],

    "SE-URBANIZACION": [
        { value: "01-CONSTRUCCION DE CALLES", label: "01-CONSTRUCCION DE CALLES" },
        { value: "02-EMPEDRADO Y ADOQUINAMIENTO DE CALLES", label: "02-EMPEDRADO Y ADOQUINAMIENTO DE CALLES"},   
        { value: "03-a) GUARNICIONES", label: "03-a) GUARNICIONES"},
        { value: "03-b) BANQUETAS", label: "03-b) BANQUETAS"},
        { value: "03-c) MUROS DE CONTENCION", label: "03-c) MUROS DE CONTENCION"},
        { value: "04-CONST. Y REMOD.DE PLAZAS CIVICAS, JARDINES Y PANTEONES", label: "04-CONST. Y REMOD.DE PLAZAS CIVICAS, JARDINES Y PANTEONES"},
        { value: "05-ALUMBRADO PUBLICO", label: "05-ALUMBRADO PUBLICO"},
        { value: "06-a) CONSTRUCCION Y REAHBILITACION DE PASOS PEATONALES", label: "06-a) CONSTRUCCION Y REAHBILITACION DE PASOS PEATONALES"},
        { value: "06-b) CONSTRUCCION Y REAHBILITACION DE PASOS VEHICULARES", label: "06-b) CONSTRUCCION Y REAHBILITACION DE PASOS VEHICULARES"},   
    ],

    "SF-PAVIMENTACION EN COLONIAS POPULARES": [
        { value: "01-CONCRETO", label: "01-CONCRETO"},
        { value: "02-ASFALTO", label: "02-ASFALTO"},
    ],

    "SG-ELECTRIFICACION": [
        { value: "01-a) CONSTRUCCION URBANA", label: "01-a) CONSTRUCCION URBANA"},
        { value: "01-b) AMPLIACION URBANA", label: "01-b) AMPLIACION URBANA"},
        { value: "02-a) CONSTRUCCION RURAL", label: "02-a) CONSTRUCCION RURAL"},
        { value: "02-b) AMPLIACION RURAL", label: "02-b) AMPLIACION RURAL"},
        { value: "03-a) POZOS AGRICOLAS-LINEAS DE TRANSMISION", label: "03-a) POZOS AGRICOLAS-LINEAS DE TRANSMISION"},
        { value: "04-NO CONVENCIONAL", label: "04-NO CONVENCIONAL"},
    ],

    "SH-VIVIENDA DIGNA": [
        { value: "01-a) REHABILITACION DE VIVIENDA URBANA", label:  "01-a) REHABILITACION DE VIVIENDA URBANA"},
        { value: "01-b) REHABILITACION DE VIVIENDA RURAL", label:  "01-b) REHABILITACION DE VIVIENDA RURAL"},
        { value: "02-a) AMPLIACION DE VIVIENDA URBANA", label:  "02-a) AMPLIACION DE VIVIENDA URBANA"},
        { value: "02-b) AMPLIACION DE VIVIENDA RURAL", label:  "02-b) AMPLIACION DE VIVIENDA RURAL"},
        { value: "02-c) AMPLIACION DE VIVIENDA LETRINIZACION", label:  "02-c) AMPLIACION DE VIVIENDA LETRINIZACION"},
    ],

    "SI-VIALIDADES URBANAS": [
        { value: "01-a) RECONSTRUCCION AVENIDAS", label: "01-a) RECONSTRUCCION AVENIDAS"},
        { value: "01-b) RECONSTRUCCION BOULEVARES", label: "01-b) RECONSTRUCCION BOULEVARES"},
        { value: "01-c) RECONSTRUCCION LIBRAMIENTOS", label: "01-c) RECONSTRUCCION LIBRAMIENTOS"},
        { value: "01-d) RECONSTRUCCION PUENTES VEHICULARES", label: "01-d) RECONSTRUCCION PUENTES VEHICULARES"},
        { value: "01-e) RECONSTRUCCION PUENTES PEATONALES", label: "01-e) RECONSTRUCCION PUENTES PEATONALES"},
        { value: "02-a) CONSTRUCCION AVENIDAS", label: "02-a) CONSTRUCCION AVENIDAS"},
        { value: "02-b) CONSTRUCCION BOULEVARES", label: "02-b) CONSTRUCCION BOULEVARES"},
        { value: "02-c) CONSTRUCCION LIBRAMIENTOS", label: "02-c) CONSTRUCCION LIBRAMIENTOS"},
        { value: "02-d) CONSTRUCCION PUENTES VEHICULARES", label: "02-d) CONSTRUCCION PUENTES VEHICULARES"},
        { value: "02-e) CONSTRUCCION PUENTES PEATONALES", label: "02-e) CONSTRUCCION PUENTES PEATONALES"},

    ],

    "SJ-INFRAESTRUCTURA EDUCATIVA": [
        { value: "01-a) REHABILITACION PREESCOLAR", label: "01-a) REHABILITACION PREESCOLAR"},
        { value: "01-b) REHABILITACION PRIMARIA", label: "01-b) REHABILITACION PRIMARIA"},
        { value: "01-c) REHABILITACION SECUNDARIA", label: "01-c) REHABILITACION SECUNDARIA",},
        { value: "01-d) REHABILITACION OTROS NIVELES", label: "01-d) REHABILITACION OTROS NIVELES",},
        { value: "02-a) CONSTRUCCION PREESCOLAR", label: "02-a) CONSTRUCCION PREESCOLAR"},
        { value: "02-b) CONSTRUCCION PRIMARIA", label: "02-b) CONSTRUCCION PRIMARIA"},
        { value: "02-c) CONSTRUCCION SECUNDARIA", label: "02-c) CONSTRUCCION SECUNDARIA"},
        { value: "02-d) CONSTRUCCION OTROS NIVELES", label: "02-d) CONSTRUCCION OTROS NIVELES"},
        { value: "03-a) EQUIPAMIENTO PREESCOLAR", label: "03-a) EQUIPAMIENTO PREESCOLAR"},
        { value: "03-b) EQUIPAMIENTO PRIMARIA", label: "03-b) EQUIPAMIENTO PRIMARIA"},
        { value: "03-c) EQUIPAMIENTO SECUNDARIA", label: "03-c) EQUIPAMIENTO SECUNDARIA"},
        { value: "03-d) EQUIPAMIENTO OTROS NIVELES", label: "03-d) EQUIPAMIENTO OTROS NIVELES"},
        
    ],

    "SL-INFRAESTRUCTURA DEPORTIVA": [
        { value: "01-REHABILITACION", label: "01-REHABILITACION"},
        { value: "02-AMPLIACION", label: "02-AMPLIACION"},
        { value: "03-CONSTRUCCION", label: "03-CONSTRUCCION"},
        
    ],

    "SO-CENTROS DE SALUD": [
        { value: "01-REHABILITACION", label: "01-REHABILITACION"},
        { value: "02-AMPLIACION", label: "02-AMPLIACION"},
        { value: "03-CONSTRUCCION", label: "03-CONSTRUCCION"},
        { value: "04-EQUIPAMIENTO", label: "04-EQUIPAMIENTO"},
    ],

    "SP-UNIDADES MEDICAS RURALES": [
        { value: "01-REHABILITACION", label: "01-REHABILITACION"},
        { value: "02-AMPLIACION", label: "02-AMPLIACION"},
        { value: "03-CONSTRUCCION", label: "03-CONSTRUCCION"},
        { value: "04-EQUIPAMIENTO", label: "04-EQUIPAMIENTO"},
    ],

    "SS-ASISTENCIA SOCIAL Y SERVICIOS COMUNITARIOS": [
        { value: "06-a) DESARROLLO COMUNITARIO CONSTRUCCION", label: "06-a) DESARROLLO COMUNITARIO CONSTRUCCION"},
        { value: "06-b) DESARROLLO COMUNITARIO REHABILITACION", label: "06-b) DESARROLLO COMUNITARIO REHABILITACION"},
        { value: "06-c) DESARROLLO COMUNITARIO AMPLIACION", label: "06-c) DESARROLLO COMUNITARIO AMPLIACION"},
    
    ],

    "S5-PROTECCION Y PRESERVACION ECOLOGIGA": [
        { value: "01-a) TRATAMIENTO DE AGUAS RESIDUALES PLANTA DE TRATAMIENTO", label: "01-a) TRATAMIENTO DE AGUAS RESIDUALES PLANTA DE TRATAMIENTO"},
        { value: "01-b) TRATAMIENTO DE AGUAS RESIDUALES LAGUNA DE OXIDACION", label: "01-b) TRATAMIENTO DE AGUAS RESIDUALES LAGUNA DE OXIDACION"},
        { value: "01-c) TRATAMIENTO DE AGUAS RESIDUALES LAGUNA DE ESTABILIZACION", label: "01-c) TRATAMIENTO DE AGUAS RESIDUALES LAGUNA DE ESTABILIZACION"},
        { value: "02-b) MANEJO DE RESIDUOS SOLIDOS RELLENO SANITARIO", label: "02-b) MANEJO DE RESIDUOS SOLIDOS RELLENO SANITARIO"},
        { value: "07-c) REFORESTACION SIEMBRA DE PLANTAS", label: "07-c) REFORESTACION SIEMBRA DE PLANTAS"},
   
    ],

    "TB-MUJERES": [
        { value: "01-PROYECTOS PRODUCTIVOS", label: "01-PROYECTOS PRODUCTIVOS"},
    ],

    "TE-APOYO A LA PRODUCCION PRIMARIA": [
        { value: "01-APOYO A PRODUCTORES AGRICOLAS", label: "01-APOYO A PRODUCTORES AGRICOLAS"},
        { value: "02-APOYO A PRODUCTORES PECUARIOS", label: "02-APOYO A PRODUCTORES PECUARIOS"},
        { value: "03-APOYO A PRODUCTORES FORESTALES", label: "03-APOYO A PRODUCTORES FORESTALES"},
        { value: "04-APOYO A PRODUCTORES PESQUEROS Y ACUICOLAS", label: "04-APOYO A PRODUCTORES PESQUEROS Y ACUICOLAS"},
        { value: "05-APOYO A LA MINERIA SOCIAL", label: "05-APOYO A LA MINERIA SOCIAL"},

    ],

    "TF-FOMENTO A LA PRODUCCION Y PRODUCTIVIDAD": [
        { value: "01-FOMENTO AGRICOLA", label: "01-FOMENTO AGRICOLA"},
        { value: "02-FOMENTO PECUARIO", label: "02-FOMENTO PECUARIO"},
        { value: "03-FOMENTO FORESTAL", label: "03-FOMENTO FORESTAL"},
        { value: "04-FOMENTO AGROINDUSTRIAL", label: "04-FOMENTO AGROINDUSTRIAL"},
        { value: "05-FOMENTO ARTESANAL", label: "05-FOMENTO ARTESANAL"},
        { value: "06-FOMENTO A LA MICROEMPRESA", label: "06-FOMENTO A LA MICROEMPRESA"},

    ],

    "TG-DESARROLLO DE AREAS DE RIESGO (PEQUEÑA IRRIGACION)": [
        { value: "01-REHABILITACION", label: "01-REHABILITACION"},
        { value: "02-CONSTRUCCION", label: "02-CONSTRUCCION"},
        { value: "03-NIVELACION DE TIERRAS", label: "03-NIVELACION DE TIERRAS"},
        { value: "04-a) OBRAS COMPLEMENTARIAS REHABILITACION DE BORDO", label: "04-a) OBRAS COMPLEMENTARIAS REHABILITACION DE BORDO"},
        { value: "04-b) OBRAS COMPLEMENTARIAS REHABILITACION DE CANAL", label: "04-b) OBRAS COMPLEMENTARIAS REHABILITACION DE CANAL"},
        { value: "04-c) OBRAS COMPLEMENTARIAS CONSTRUCCION DE BORDO", label: "04-c) OBRAS COMPLEMENTARIAS CONSTRUCCION DE BORDO"},
        { value: "04-d) OBRAS COMPLEMENTARIAS CONSTRUCCION DE CANAL", label: "04-d) OBRAS COMPLEMENTARIAS CONSTRUCCION DE CANAL"},

    ],

    "TH-DESARROLLO DE AREAS DE TEMPORAL": [
        { value: "01-DESMONTE", label: "01-DESMONTE"},
        { value: "02-DESPIEDRE", label: "02-DESPIEDRE"},
        { value: "03-NIVELACION DE TIERRAS", label: "03-NIVELACION DE TIERRAS"},
        { value: "04-SUBSOLEO", label: "04-SUBSOLEO"},
        { value: "05-CONSERVACION DEL SUELO Y EL AGUA", label: "05-CONSERVACION DEL SUELO Y EL AGUA"},

    ],

    "TI-PROTECCION DE AREAS Y CAUCES FEDERALES": [
        { value: "01-AREAS DE CULTIVO", label: "01-AREAS DE CULTIVO"},
        { value: "02-POBLADO", label: "02-POBLADO"},
        { value: "03-DRENES PLUVIALES", label: "03-DRENES PLUVIALES"},
        
    ],
    
    "UB-CAMINOS RURALES": [
        { value: "01-a) RECONSTRUCCION CAMINOS", label: "01-a) RECONSTRUCCION CAMINOS"},
        { value: "01-b) RECONSTRUCCION PUENTES", label: "01-b) RECONSTRUCCION PUENTES"},
        { value: "01-c) RECONSTRUCCION VADOS", label: "01-c) RECONSTRUCCION VADOS"},
        { value: "02-a) CONSTRUCCION CAMINOS", label: "02-a) CONSTRUCCION CAMINOS"},
        { value: "02-b) CONSTRUCCION PUENTES", label: "02-b) CONSTRUCCION PUENTES"},
        { value: "02-c) CONSTRUCCION VADOS", label: "02-c) CONSTRUCCION VADOS"},
        { value: "03-a) CONSERVACION CAMINOS", label: "03-a) CONSERVACION CAMINOS"},
        { value: "03-b) CONSERVACION PUENTES", label: "03-b) CONSERVACION PUENTES"},
        { value: "03-c) CONSERVACION VADOS", label: "03-c) CONSERVACION VADOS"},
        { value: "04-ESTUDIOS Y PROYECTOS", label: "04-ESTUDIOS Y PROYECTOS"},

    ],

    "UE-SITIOS HISTORICOS Y CULTURALES": [
        { value: "01-RESTAURACION", label: "01-RESTAURACION"},
        { value: "02-CONSTRUCCION", label: "02-CONSTRUCCION"},
        
    ],

    "UH-INFRAESTRUCTURA PENINTENCIARIA": [
        { value: "01-REHABILITACION", label: "01-REHABILITACION"},
        { value: "02-AMPLIACION", label: "02-AMPLIACION"},
        { value: "03-CONSTRUCCION", label: "03-CONSTRUCCION"},

    ],

    "U9-DEFINICION Y CONDUCCION DE LA PLANEACION DEL DESARROLLO REGIONAL": [
        { value: "01-ESTUDIOS Y PROYECTOS", label: "01-ESTUDIOS Y PROYECTOS"},
        { value: "02-ADMINISTRACION", label: "02-ADMINISTRACION"},
        { value: "03-SERVICIOS", label: "03-SERVICIOS"},
        
    ],
    "3Z-REGULACION Y PRESERVACION ECOLOGICA": [
        { value: "01-REGULACION Y PREVENCION DE LA CONTAMINACION", label: "01-REGULACION Y PREVENCION DE LA CONTAMINACION"},
        { value: "02-PRESERVACION Y RESTAURACION DE ECOSISTEMAS", label: "02-PRESERVACION Y RESTAURACION DE ECOSISTEMAS"},
        { value: "03-PREVENCION DE LA CONTAMINACION DEL AGUA", label: "03-PREVENCION DE LA CONTAMINACION DEL AGUA"},
        { value: "04-CONTROL DE RESIDUOS SOLIDOS", label: "04-CONTROL DE RESIDUOS SOLIDOS"},
    ],

    "5C-ESTABLECIMIENTOS TURISTICOS Y DE ESPARCIMIENTO": [
        { value: "01-CONSTRUCCION Y AMPLIACION DE ESTABLECIMIENTOS TURISTICOS", label: "01-CONSTRUCCION Y AMPLIACION DE ESTABLECIMIENTOS TURISTICOS"},
        { value: "02-CONSERVACION, REHABILITACION Y MANTENIMIENTO", label: "02-CONSERVACION, REHABILITACION Y MANTENIMIENTO",},

    ],

    "5G-AMPLIACION Y MEJORAMIENTO DE LA PLANTA FISICA PARA LA INVESTIGACION CIENTIFICA Y TECNOLOGICA": [
        { value: "01-CONSTRUCCION Y EQUIPAMIENTO DE ESPACIOS PARA LA INVESTIGACION", label: "01-CONSTRUCCION Y EQUIPAMIENTO DE ESPACIOS PARA LA INVESTIGACION"},
        { value: "02-CONSERVACION Y MANTENIMIENTO DE ESPACIOS PARA LA INVESTIGACION", label: "02-CONSERVACION Y MANTENIMIENTO DE ESPACIOS PARA LA INVESTIGACION"},

    ],

    "5I-EDIFICIOS PARA SERVICIOS DE SALUD Y SEGURIDAD SOCIAL": [
        { value: "01-a) ESTANCIAS DE BIENESTAR INFANTIL AMPLIACION", label: "01-a) AMPLIACION"},
        { value: "01-b) ESTANCIAS DE BIENESTAR INFANTIL REHABILITACION", label: "01-b) REHABILITACION"},
        { value: "01-c) ESTANCIAS DE BIENESTAR INFANTIL CONSTRUCCION", label: "01-c) CONSTRUCCION"},
        { value: "02-a) VELATORIOS AMPLIACION", label: "02-a) VELATORIOS AMPLIACION"},
        { value: "02-b) VELATORIOS REHABILITACION", label: "02-b) VELATORIOS REHABILITACION"},
        { value: "02-c) VELATORIOS CONSTRUCCION", label: "02-c) VELATORIOS CONSTRUCCION"},
        { value: "03-a) CENTROS CULTURALES Y DE BIENESTAR FAMILIAR AMPLIACION", label: "03-a) CENTROS CULTURALES Y DE BIENESTAR FAMILIAR AMPLIACION"},
        { value: "03-b) CENTROS CULTURALES Y DE BIENESTAR FAMILIAR REHABILITACION", label: "03-b) CENTROS CULTURALES Y DE BIENESTAR FAMILIAR REHABILITACION"},
        { value: "03-c) CENTROS CULTURALES Y DE BIENESTAR FAMILIAR CONSTRUCCION", label: "03-c) CENTROS CULTURALES Y DE BIENESTAR FAMILIAR CONSTRUCCION"},
        { value: "04-a) CENTROS DE ASISTENCIA SOCIAL, REHABILITACION Y EDUCACION ESPECIAL AMPLIACION", label: "04-a) CENTROS DE ASISTENCIA SOCIAL, REHABILITACION Y EDUCACION ESPECIAL AMPLIACION"},
        { value: "04-b) CENTROS DE ASISTENCIA SOCIAL, REHABILITACION Y EDUCACION ESPECIAL REHABILITACION", label: "04-b) CENTROS DE ASISTENCIA SOCIAL, REHABILITACION Y EDUCACION ESPECIAL REHABILITACION"},
        { value: "04-c) CENTROS DE ASISTENCIA SOCIAL, REHABILITACION Y EDUCACION ESPECIAL CONSTRUCCION", label: "04-c) CENTROS DE ASISTENCIA SOCIAL, REHABILITACION Y EDUCACION ESPECIAL CONSTRUCCION"},

    ],

    "5K-EDIFICIOS ADMINISTRATIVOS": [
        { value: "01-a) AMPLIACION", label: "01-a) AMPLIACION"},
        { value: "01-b) CONSTRUCCION", label:"01-b) CONSTRUCCION"},
        { value: "02-a) CONSERVACION", label:"02-a) CONSERVACION"},
        { value: "02-b) REHABILITACION", label:"02-b) REHABILITACION"},
        { value: "02-c) MANTENIMIENTO", label:"02-c) MANTENIMIENTO"},
        { value: "03-RECONSTRUCCION", label:"03-RECONSTRUCCION"},

    ],

    "5L-SUELO PARA DESARROLLO URBANO, VIVIENDA Y ECOLOGIA": [
        { value: "a) ADQUISICION PARA URBANIZACION", label: "a) ADQUISICION PARA URBANIZACION"},
        { value: "b) ADQUISICION PARA RESERVA TERRITORIALES (VIVIENDA)", label:"b) ADQUISICION PARA RESERVA TERRITORIALES (VIVIENDA)"},
        { value: "c) ADQUISICION PARA EQUIPAMIENTO URBANO", label:"c) ADQUISICION PARA EQUIPAMIENTO URBANO"},

    ],

    "6P-CANALIZACION DE RECURSOS FINANCIEROS": [
        { value: "01-AGRICOLA, GANADERA, SILVICOLA Y PESQUERA", label: "01-AGRICOLA, GANADERA, SILVICOLA Y PESQUERA"},
        { value: "02-MINERIA", label: "02-MINERIA"},
        { value: "03-INDUSTRIA", label: "03-INDUSTRIA"},
        { value: "04-a) DEUDA A BANCA COMERCIAL O DE DESARROLLO", label: "04-a) DEUDA A BANCA COMERCIAL O DE DESARROLLO"},
        { value: "04-b) DEUDA A CONTRATISTA O PROVEEDORES", label: "04-b) DEUDA A CONTRATISTA O PROVEEDORES"},
        { value: "04-c) DEUDA A INSTITUCIONES O DEPENDENCIAS", label: "04-c) DEUDA A INSTITUCIONES O DEPENDENCIAS"},
        
    ],

    "0101-SISTEMA DE AGUA POTABLE": [],
    "0102-POZO PROFUNDO DE AGUA POTABLE": [],
    "0103-DEPOSITO O TANQUE DE AGUA POTABLE": [],
    "0104-NORIAS": [],
    "0105-1.5-BOMBAS Y EQUIPO": [],
    "0136-PROYECTOS EJECUTIVO": [],
    "0140-OTROS(ESPECIFICAR)": [],
    "0308-RED DE DRENAJE PRUVIAL": [],
    "0309-RED DE DRENAJE SANITARIO": [],
    "0310-LETRINAS": [],
    "0336-PROYECTO EJECUTIVO": [],
    "0340-OTROS(ESPECIFICAR)": [],
    "0411-CALLES Y CAMINOS": [],
    "0412-PUENTES PEATONALES O VEHICULARES": [],
    "0413-PASOS PEATONALES Y/O VEHICULARES": [],
    "0414-RELLENO SANITARIO": [],
    "0415-TRATAMIENTO DE AGUAS RESIDUALES": [],
    "0436-PROYECTO EJECUTIVO": [],
    "0440-OTROS(ESPECIFICAR)": [],
    "0519-RED DE ELECTRICIDAD": [],
    "0520-ALUMBRADO PUBLICO": [],
    "0540-OTROS(ESPECIFICAR)": [],
    "0621-CENTROS DE SALUD": [],
    "0622-DISPENSADOR MEDICO Y UNIDADES MEDICAS RURALES": [],
    "0623-LABORATORIOS DE ANALISIS CLINICOS": [],
    "0636-PROYECTO EJECUTIVO": [],
    "0640-OTROS(ESPECIFICAR)": [],
    "0724-AULAS": [],
    "0725-SANITARIOS DENTRO DE ESCUELAS": [],
    "0726-BARDAS DE ESCUELA": [],
    "0727-ESCALERAS Y ANDADORES DENTRO DE ESCUELAS": [],
    "0736-PROYECTO EJECUTIVO": [],
    "0740-OTROS(ESPECIFICAR)": [],
    "0829-PISO FIRME": [],
    "0830-VIVIENDA": [],
    "0931-CAMINOS RURALES": [],
    "0936-PROYECTO EJECUTIVO": [],
    "0940-OTROS(ESPECIFICAR)": [],
  };
  